@startuml
abstract class  "Enemigo"
abstract class "Mago"
class "Mago Fuego"
class "Mago Healer"
class "Mago Hielo"
class "Mago Piedra"
class "Proyectil"
class "Slime"
interface "Colision"
Enemigo <|-- Slime
Mago <|-- "Mago Fuego"
Mago <|-- "Mago Healer"
Mago <|-- "Mago Hielo"
Mago <|-- "Mago Piedra"
Colision <|.. Enemigo
Colision <|.. Proyectil
@enduml